### ISSUE TITLE
Two Crashes

### ISSUE THREAD

**Issue by Puremin0rez** [SonarSonic/Practical-Logistics-2#10]
These two crashes occurred for a user of my modpack when messing around with the mod in Single Player.

Attached are two crash reports.
[crash-2017-04-12_00.27.52-client.txt](https://github.com/SonarSonic/Practical-Logistics-2/files/918335/crash-2017-04-12_00.27.52-client.txt)
[crash-2017-04-12_00.49.47-client.txt](https://github.com/SonarSonic/Practical-Logistics-2/files/918334/crash-2017-04-12_00.49.47-client.txt)

**Comment by SonarSonic** [comment]
Thanks for reporting should be fixed in the next update with any luck
