### ISSUE TITLE
Guide crashes in Example Configurations screen

### ISSUE THREAD

**Issue by JackTheRedCreeper** [SonarSonic/Practical-Logistics-2#11]
Tested with latest and recommended forge, and no other mods than Practical Logistics 2.0.1
Every time I reach the Example Configurations part of the guide, I crash, be it via the [<<] [>>] buttons or by directly clicking on it on the index.

Logs:
https://pastebin.com/508aacui
https://pastebin.com/SFnRzRd1

**Comment by SonarSonic** [comment]
What version of MCMultipart are you running. Looks like it needs updating. Or if you are already on 1.4.0 re-download the JAR
