### ISSUE TITLE
Crash after placing Clock

### ISSUE THREAD

**Issue by Kicos** [SonarSonic/Practical-Logistics-2#16]
Minecraft just crashed after i placed the Clock on the Tinker's Construct Smeltery.
Game kept crashing until i disabled optifine.

Any Ideas? Would like to keep playing with Optifine.

Crash report: https://gist.github.com/Kicos/6be2a2d03cbd62891327e70d1ba1b9fc#file-crash-2017-04-19_15-35-47-client-txt

**Comment by AEnterprise** [comment]
That would be a bug with optifine, you'll have to report it there for a fix: https://github.com/sp614x/optifine
