### ISSUE TITLE
The Book's Font Is Too Small To See.

### ISSUE THREAD

**Issue by TartaricAcid** [SonarSonic/Practical-Logistics-2#2]
![bug](http://i.imgur.com/gru5gMn.png)
As shown in this picture.

>Minecraft does not have anti-aliasing font rendering method. Using non-integer GL scale ratio will break the font. A line with 0.9 pixel width may be 0 width when rendering.
This issue will be more obvious when you turn on the unicode font in language settings (or you are under some unicode-only language like Chinese), with the game's window height less than 960 px.

>From this comment: [[BUG] Manual's font size is too small to see](https://github.com/Ellpeck/ActuallyAdditions/issues/461#issuecomment-265403566)

To fix this, my suggestion is: Please use 1.0x or 2.0x scale ratio when rendering the font, or use language file to control scale ratio.

**Comment by TartaricAcid** [comment]
Ref: Ellpeck/ActuallyAdditions#461
Ref: OpenMods/OpenBlocks#655

**Comment by SonarSonic** [comment]
Fixed in dev

**Comment by TartaricAcid** [comment]
Thanks
