### ISSUE TITLE
Blocks not dropping

### ISSUE THREAD

**Issue by BloodWorkXGaming** [SonarSonic/Practical-Logistics-2#23]
Often some blocks don't drop when mined.

This is the case for the Node, screen and readers.
The cables drop fine tho.

PracLog2: 1.10.2-2.0.2
SonarCore: 1.10.2-3.2.7
Forge: 12.18.3.2297
No error gets thrown therefore can't attach a log

**Comment by SonarSonic** [comment]
Fixed in dev
