### ISSUE TITLE
Transfer Nodes aren't transferring power.

### ISSUE THREAD

**Issue by Dilnu** [SonarSonic/Practical-Logistics-2#27]
Hi, I'm having issues with transfer nodes not transfering energy. I've confirmed that the node is working by testing it with items but the power transfer isn't working.

I'm trying to connect an advanced power cube from calculator to a precision chamber.

The transfer node is on the precision chamber set to add. And a normal node is on the power cube. These are connected by a data cable.

Minecraft: 1.10.2
Forge: 12.18.3.2297
Sonar Core: 3.2.7
Calculator: 3.2.2
Practical Logistics 2: 2.0.2
Logfiles are here: 
https://pastebin.com/GC9tvBBX
https://pastebin.com/FCX2Tq4b

**Comment by SonarSonic** [comment]
Currently energy transfer in practical logistics is disabled as I've got another mod "Flux Networks" for this. 
https://minecraft.curseforge.com/projects/flux-networks

**Comment by Dilnu** [comment]
Could you remove the UI from transfer nodes then? It's confusing.
