### ISSUE TITLE
No way of getting Sapphire?

### ISSUE THREAD

**Issue by craft90** [SonarSonic/Practical-Logistics-2#34]
I recently started a new instance with a couple of 1.10.2 mods and one of these are Practical Logistics 2. However I quickly ran into a problem with the sapphires. Sure I find the ores however they drop as ore blocks. Sure you can use the Forging Hammer to get the dusts but certain recipes demands sapphire gems which there's no way of getting. Unless I use the Immersive Engineering Crusher or the EnderIO SAG Mill. Which means that with neither of those available it's just not possible to get the gems. Unless there's some other way I'm not familiar with. I thought smelting the dust may work but it doesn't. You can't smelt the dusts or the ores. There's just no way of finding that out how to get those gems as the wiki doesn't have that info and the Guide book requires Sapphire gems.

It's the latest version of the mod aswell.

EDIT: I checked the guide via Creative mode. So... the ore is supposed to turn into sapphires in the Forging Hammer but instead you get sapphire dust. Seems like an oversight.

**Comment by SonarSonic** [comment]
Ohhh thanks for pointing this out. Ores are supposed to drop Sapphires, this has been fixed in dev now.
