### ISSUE TITLE
energy is not transmitted

### ISSUE THREAD

**Issue by mgdgfbhevdyeh** [SonarSonic/Practical-Logistics-2#36]
![2017-08-21_17 16 49](https://user-images.githubusercontent.com/20567492/29512596-2471fa06-8695-11e7-8c1a-360780e5eeec.png)
![2017-08-21_17 16 52](https://user-images.githubusercontent.com/20567492/29512591-244a1400-8695-11e7-86d3-ad04cc532f1c.png)
![2017-08-21_17 16 58](https://user-images.githubusercontent.com/20567492/29512592-244ed6de-8695-11e7-8e9f-0640408d1c7b.png)
![2017-08-21_17 17 02](https://user-images.githubusercontent.com/20567492/29512593-24610930-8695-11e7-9c73-acee69270807.png)
![2017-08-21_17 17 37](https://user-images.githubusercontent.com/20567492/29512594-246a1944-8695-11e7-82dd-c2b0fd17954a.png)
![2017-08-21_17 18 48](https://user-images.githubusercontent.com/20567492/29512595-246cf506-8695-11e7-8a28-ac602c674cb1.png)
The energy is not transmitted
In the same circumstances, fluids and items can be transported

**Comment by SonarSonic** [comment]
Transfer Node energy transfer is currently unimplemented. As Flux Networks provides this function.
