### ISSUE TITLE
1.12

### ISSUE THREAD

**Issue by D3nnis3n** [SonarSonic/Practical-Logistics-2#39]
As i saw Calculator and flux Networks have been Upgraded, i Wanted to ask if practical logistics is going to follow?

**Comment by D3nnis3n** [comment]
Any News or plans?

**Comment by MakerTim** [comment]
No new branch, but hope that its a local branch can still be a thing

**Comment by D3nnis3n** [comment]
Obviously this is not in the works.

**Comment by SonarSonic** [comment]
1.12.2 is in alpha now.
