### ISSUE TITLE
1.12 - Screens cannot be destroyed

### ISSUE THREAD

**Issue by D3nnis3n** [SonarSonic/Practical-Logistics-2#44]
Screens cannot be destroyed by any tool or in creative mode - need to use Worldedit to remove them.

**Comment by SonarSonic** [comment]
Did you try destroying them at the back?

**Comment by SonarSonic** [comment]
As they need to be left clicked at the front you can only break them at the back.

**Comment by D3nnis3n** [comment]
Mh, no. I just tried a Bit around. They dont seemto work yet. There is no
no data screen and they cant ne right clicked to configure. Ill try
removing them from the back later.

Ollie Lansdell <notifications@github.com> schrieb am Di., 24. Apr. 2018,
14:20:

**Comment by SonarSonic** [comment]
have you tried the large display? the small ones and holographic and little bit broken

**Comment by D3nnis3n** [comment]
Yes, i tried the large one and the small one. The last one i do not really
get how it Works and the large one is empty and Not rightclickable.

Ollie Lansdell <notifications@github.com> schrieb am Di., 24. Apr. 2018,
14:33:

**Comment by SonarSonic** [comment]
The new version is out now, which should have fixed the breaking of Display's issue and quite a few others, inc. large/small one not being right clickable.

**Comment by D3nnis3n** [comment]
Okay, i got them to show something. But they only show in FE for Energy (they did show in MJ last version - but they do use that as Million Joule and not MegaJoule like Mekanism does, so the value is not right or better is not the same unit as Mekanism uses.)

**Comment by SonarSonic** [comment]
Good progress, the screens were the big one! The Energy Reader hasn't been touched much since the port and I will slowly get on to improving that too.
