### ISSUE TITLE
Inventory desync between client and server

### ISSUE THREAD

**Issue by Xiaminou** [SonarSonic/Practical-Logistics-2#45]
https://youtu.be/b4YejOJCFeY

Minecraft: 1.12.2
Forge: 2669
Mods: [list.txt](https://github.com/SonarSonic/Practical-Logistics-2/files/1942697/list.txt)

**Comment by SonarSonic** [comment]
Thank you for this, it's incredibly useful to see the issues you're encountering. Keep letting me know all the issues you find. Is this single player or server?

**Comment by SonarSonic** [comment]
Also would it be possible for you to do a similar test but with the Large Display screen?

**Comment by Xiaminou** [comment]
It was done on a server, and I tried the Large Display Screen but it didn't work at all. Might have been another case of desync.

**Comment by SonarSonic** [comment]
Thank you, I just tried and was able to recreate most of these, also was only able to use the Large Display screen after a relog.

**Comment by Xiaminou** [comment]
https://youtu.be/R2Gx8eFaVkw

**Comment by SonarSonic** [comment]
Again really appreciate this video. I've added all the issues I noticed here...
https://github.com/SonarSonic/Practical-Logistics-2/wiki/1.12.X---Port

**Comment by Xiaminou** [comment]
Have you considered adding vertical alignment as well? I don't see it in the planned feature list. In the second video I modified the text and it turned out it wasn't vertically centered, so I couldn't get it to look like I wanted to. Being able to vertically align to top, bottom or center would be a nice addition.

**Comment by SonarSonic** [comment]
@Xiaminou yes that was a bug, it should have aligned when you changed it, essentially it's only "counting lines" if they have text in them. And yes all alignment options are planned, in fact the code is already there they are just not shown in the GUIs yet as it just isn't the main priority, but we'll get there!

**Comment by SonarSonic** [comment]
New version is out, hopefully should have fixed almost every issue in both of your videos, let me know how you get on!

https://minecraft.curseforge.com/projects/practical-logistics-2/files/2555869

**Comment by Xiaminou** [comment]
I'm still getting desync when breaking things.

**Comment by SonarSonic** [comment]
What kind of desync? On 3.0.3 with Sonar Core 5.0.9?

**Comment by Xiaminou** [comment]
looks like it's only when breaking stuff with the wrench.

https://youtu.be/XXjDDS5Ca50

You should make it so the wrench's right-click harvests the part. Like most popular mods do.

**Comment by SonarSonic** [comment]
Ah the inventory de-sync glitch, I'm aware of this one and still haven't worked it out yet.

**Comment by Xiaminou** [comment]
I've also been meaning to ask, is there a way to print out multiple informations on a single screen (not multi-screen). Having customizable screen areas is great but if you're only capable of printing a single information I feel like it loses its value.
The first time I used this mod I thought it worked the other way around. I thought you put the information readers on the block you're trying to read and just linked the screen to it, so you'd be able to put multiple information readers around your machine but you'd only need one screen to read them all. Does that make sense?
The idea being that you would only need 1 block space for the screen.

**Comment by SonarSonic** [comment]
You can connect multiple readers, ie, connect to your blocks with nodes, connect the readers, then where you would connect the display instead put a data cable and join all of the reader's outputs together (the advantage of this system over readers on blocks is that, I can be more efficient and also allow readers to read blocks all over the place and it's easier to change what your reading without reconfiguring.) 

However, I am also working on a more advanced reader which will be able to create any type of information and effectively act as multiple readers in one block. Then the final upgrade will be a display on which you can create info, without connecting anything.

**Comment by Xiaminou** [comment]
Oh, okay I didn't know you could do it like that. Can you put multiple readers in line or do they have to be parallel?

**Comment by SonarSonic** [comment]
You may be able to put them in a line, but it won't necessarily work when you relog, as technically they're not meant to connect like that
