### ISSUE TITLE
Crash while placing blank screen "not rendered screen"

### ISSUE THREAD

**Issue by ItzKdoge20YT** [SonarSonic/Practical-Logistics-2#46]
When i place the screen, it looks normal but when i re-place the screen, the screen could not render but when i put the fluid or other reader, it crashed.

Crash Report : https://pastebin.com/NB9qpYuZ
MC version : 1.12.2
Mod Version : 3.0.0
Forge Version : 1.12-forge1.12.2-14.23.3.2673

**Comment by ItzKdoge20YT** [comment]
![2018-04-26_15 03 27](https://user-images.githubusercontent.com/13083280/39293440-16587dbe-4963-11e8-8dec-d5beb29cf5a9.png)
this is blank screen looks like, Without GUIS on side, placing some connector will crash the game, idk if that is de-sync or something

**Comment by ItzKdoge20YT** [comment]
reloading seems fix it, idk why if that was a de-sync or something, if that de-sync that's mean it might be a problem...

**Comment by SonarSonic** [comment]
Thanks for reporting, already fixed this one as it happens. You can see current issues with the alpha I'm working through [here](https://github.com/SonarSonic/Practical-Logistics-2/wiki/1.12.X---Port), hope to have a new version soon.

**Comment by ItzKdoge20YT** [comment]
New Version seems fixed it, thanks
i just updated the mod to 3.0.1 and sonar core, and it works normally

**Comment by SonarSonic** [comment]
Good to hear, let me know if you find any other issues!
