### ISSUE TITLE
Two Inventory Readers on same network weirdness

### ISSUE THREAD

**Issue by bpwhelan** [SonarSonic/Practical-Logistics-2#5]
On the same network, two Inventory readers (mostly for symmetry) This is the first-placed one.
![image](https://cloud.githubusercontent.com/assets/8314499/24239912/1b3b9a54-0f86-11e7-8b38-5f4e50577bac.png)

This is the second placed one.
![image](https://cloud.githubusercontent.com/assets/8314499/24239919/23708e00-0f86-11e7-9218-5962fd09bae5.png)

Should be pretty easy to recreate, I'm using Storage Crates from Actually Additions and Nodes (not Arrays).

I've tried taking more items than the network has and it does not allow me, so it's definitely just visual.

**Comment by SonarSonic** [comment]
It looks like some items are doubling and others arnt so Any chance you could take a picture of your actual configuration as that is pretty weird. Also could you try breaking and replacing the cables on both readers.

**Comment by bpwhelan** [comment]
https://youtu.be/si3mJcQN1xo

This is after a complete re-place of the network

Edit: after a little bit of testing, it seems like the problem is when there is an item in two different chests.
Works with Vanilla chests as well.

https://youtu.be/Sf73OO6I_bQ

Hope this helps

**Comment by SonarSonic** [comment]
Thanks! Fixed in dev
