### ISSUE TITLE
[1.12.2] Conflict with BibloCraft: Placed Clocks causes a chunk loading issue & crash if entering the dimension near the broken chunk.

### ISSUE THREAD

**Issue by SonicX8000** [SonarSonic/Practical-Logistics-2#50]
Referenced Issue:
https://github.com/Nuchaz/BiblioCraft/issues/562

Minecraft: 1.12.2
Forge: 14.23.3.2673

Mods:
BiblioCraft[v2.4.3][MC1.12.0]
MCMultiPart-2.5.1
practicallogistics2-1.12.2-3.0.3
sonarcore-1.12.2-5.0.9

Crash Report:
https://pastebin.com/y3pxjtgL

-----
For some odd reason, placing any of the BibloCraft's Clocks will cause a problem with the chunks near it. When that chunk un-loads and you re-load it... the chunkthat the Clock was placed in, as well as the chunks around it will be invisible.

If you enter the dimension near the broken chunks... say by coming from the nether portal that was created near those chunks... the game crashes.

The chunks will reload if you load up the world again, however the Clocks placed there become invisible until you get near them and they won't be in the correct place. Framed Clocks will also lose their custom textures.

If I remove the Practical Logistics 2 mod, this issue doesn't occur.

Here's a screenshot of the chunk error due to a BibloCraft Clock being placed there.
![](https://cdn.discordapp.com/attachments/377171551155650560/443492744929738758/PE2Biblocraftbug.png)

**Comment by SonarSonic** [comment]
This is caused by the Bibliocraft Clock and the PL2 Clock sharing the same TileEntity id of "Clock". As PL2 is a smaller mod, i'll be changing my clock id to "PL2Clock".
