### ISSUE TITLE
Crash when hooking up fluid reader to entity node

### ISSUE THREAD

**Issue by lag42** [SonarSonic/Practical-Logistics-2#6]
I got confused about what reader to put on the entity node and I tried the fluid reader and then it crashed and thanks to Minecraft's horrible new launcher I can't get you a crash log
EDIT:Crash report here:
[crash-2017-03-23_09.29.04-server.txt](https://github.com/SonarSonic/Practical-Logistics-2/files/865434/crash-2017-03-23_09.29.04-server.txt)

**Comment by thebrightspark** [comment]
Regarding the crash log, check your "crash-reports" directory in your mod pack folder. All crash reports are saved here.

**Comment by SonarSonic** [comment]
Fixed in dev
