### ISSUE TITLE
Your MCMod File is invalid

### ISSUE THREAD

**Issue by AlienXAXS** [SonarSonic/Practical-Logistics-2#60]
https://github.com/SonarSonic/Practical-Logistics-2/blob/09c1badf07098ea3b054ceb4af781924a7920eb2/src/main/resources/mcmod.info#L11

The file contains an extra comma after the banner image file path, this should not be there and causes the mod to not be loaded by Forge.

`[19:20:45] [main/ERROR] [FML]: The mcmod.info file in practicallogistics2-1.12.2-3.0.4.jar cannot be parsed as valid JSON. It will be ignored`

**Comment by C0rn3j** [comment]
Just ran into this. Seeing as this is fixed in master, would you please do a bugfix release? ^^
