### ISSUE TITLE
Server crash on using Energy Reader on Induction Matrix from Mekanism

### ISSUE THREAD

**Issue by DDarkstorm** [SonarSonic/Practical-Logistics-2#63]
Practical Logistics 2: 3.0.4 
sonarcore: 5.0.10
MCMultiPart: 2.5.1

I tried to use Practical Logistics 2 on my server with my friend and it worked fine for all energy blocks but I keep getting crashes from the server side when using the energy reader on a induction matrix full of energy. The crash happens only when after putting a screen, I try to either show me the informations or open the reader GUI.

Here is the crash-report:
https://pastebin.com/N4aALryS

**Comment by DDarkstorm** [comment]
The crash also happens on single player mode

The crash-report:
https://pastebin.com/525AsLEb

**Comment by DDarkstorm** [comment]
I tried using it on a minecraft with only Practical Logistics 2, Sonarcore, MCMultiPart and Mekanism and it also did crash.

**Comment by Fear59** [comment]
The crash also happens to me

**Comment by mudgw2** [comment]
Same crash every time.

**Comment by SalmonSays** [comment]
I get this crash when using the energy reader at all, even on a vanilla furnace

**Comment by SonarSonic** [comment]
Fixed in dev
