### ISSUE TITLE
Screens not updating 1.12.2

### ISSUE THREAD

**Issue by Fear59** [SonarSonic/Practical-Logistics-2#66]
I've tried all  Readers seem to not update when a go in to the screen editing then it updates for a split second and then a exit the screen and its stuck not updating at all so i don't know if this is a bag or something in my mod pack is causing the issue

a remove all mods except this 3

practical-logistics-2-1.12.2-3.0.4
Sonar-Core-1.12.2-5.0.10
MCMultiPart-1.12.2-2.5.1

**Comment by gary-conlon** [comment]
I'm having this same issue

**Comment by marcin212** [comment]
I'm having the same issue on multiplayer.

**Comment by Xirenec** [comment]
I have same issue, except it updates info from inventory reader hooked up to chest. Doesn't update with furnace/energy storages.

practical-logistics-2-1.12.2-3.0.4
Sonar-Core-1.12.2-5.0.12
MCMultiPart-1.12.2-2.5.1

**Comment by Fear59** [comment]
a am update forge and see if it resolves the problem

**Comment by UnskilledWolf** [comment]
I am having the same Problem.

**Comment by gary-conlon** [comment]
@SonarSonic Can you try to look at this issue as it makes a lot of things in your mod pointless and it would be very good if it worked.

**Comment by SonarSonic** [comment]
Fixed in dev, sorry the mods been out of action so long. It should work as expected with the next update
