### ISSUE TITLE
Redstone Signaller allows saving without setting info object, causes NPE.

### ISSUE THREAD

**Issue by ruifung** [SonarSonic/Practical-Logistics-2#69]
Steps to reproduce:
1. Place redstone signaller.
2. Select info source.
3. DO NOT select info object.
4. Enter condition.
5. Save
6. Watch NPE happen. Although in my case the erroring TE just gets removed and the whole block, data cables and all just gets removed.

**Comment by SonarSonic** [comment]
Fixed in dev
