### ISSUE TITLE
Kicked immediately from server

### ISSUE THREAD

**Issue by thebrightspark** [SonarSonic/Practical-Logistics-2#7]
MC v1.10.2
Forge v12.18.3.2254
Practical Logistics 2 v2.0.0
EnderIO v3.1.179
Refined Storage v1.2.24
plus more mods. I can provide a list if you need to know others.

So I have a simple setup of a display showing my power stored in a Vibrant Capacitor Bank (EnderIO) and a Data Emitter connected up to my Crafting Grid (Refined Storage) so I can access it using the Wireless Storage Reader.

However sometimes when I leave and later re-join the server, I join and then get immediately kicked (before the world starts loading) with the following error on my screen:
Internal Exception: java.IOException: An existing connection was forcibly closed by the remote host

On the server console, this appears:
http://pastebin.com/5JTaERrU

We get around the issue by when it starts happening, I get teleported by an OP to somewhere out of render distance of my base when I try to login, and then after it's kicked me I log back in fine to where I was teleported to. I can then safely travel back to my base and re-configure the displays.

Here's what I have setup:
https://imgur.com/a/GJuKn
These are the only blocks I have from your mod in my base.

**Comment by SonarSonic** [comment]
Fixed in dev
