### ISSUE TITLE
Question: Automating the item extraction from the Forging Hammer

### ISSUE THREAD

**Issue by IcedReaper** [SonarSonic/Practical-Logistics-2#70]
Hello,

I have a quick question. I'm trying to automate the forging hammer.
I can automate the input via a regular hopper, but I can't automate the output.
I tried regular hoppers below the forging hammer, I tried the practical logistics transfer node and data cable, and I tried using other mods items to get the items automatically.

Sadly I wasn't able to automate the item extraction.
Is there a way to automate it, is this a feature request, or was is left out on purpose?

Thanks in advance and best regards,
IcedReaper.

**Comment by ouroborus** [comment]
I, too, would like to see automation capability. Especially using other mods' item transfer capabilities.

**Comment by SonarSonic** [comment]
Fixed in dev
