### ISSUE TITLE
Industrial Foregoing Black Hole Controller Air Anomaly

### ISSUE THREAD

**Issue by ghost** [SonarSonic/Practical-Logistics-2#75]
Preliminary Information:
Minecraft Version: 1.12.2
Forge Version: forge-1.12.2-14.23.5.2768
Practical Logistics version: 3.0.4
Industrial Foregoing version: 1.11.5

When attaching an inventory reader to a black hole controller via data cable and node, the inventory reader intermittently reads the item properly, reads the correct count but instead as 'air', or starts filling up with numerous 'air' counts.

For example, I have black hole controllers storing cobblestone and dirt. Both are setup identically.

The cobblestone black hole controller's inventory reader shows this:
![2018-11-14_06 19 12](https://user-images.githubusercontent.com/24266948/48437463-84640d80-e7d5-11e8-8452-ac78e70a69ad.png)

The dirt black hole controller's inventory reader displays this:
![2018-11-14_06 22 01](https://user-images.githubusercontent.com/24266948/48437511-9e055500-e7d5-11e8-886b-ea7869564d7b.png)

Despite identical setups, you can see that these two devices behave differently, with one working and one not. Both readers have had the same 'air' anomaly previously, but after some tinkering I had got them working. However, once the chunks were unloaded (I left the server) the readers went back to reading in massive amounts of 'air'.

The inventory reader still works correctly with chests, etc. So I believe it's just a compatibility issue with the black hole controller, probably due to the fact it actually holds 9 of the black hole units that then hold the items themselves:

![2018-11-14_06 28 22](https://user-images.githubusercontent.com/24266948/48437823-811d5180-e7d6-11e8-8749-da7bb52fb011.png)

![2018-11-14_06 28 25](https://user-images.githubusercontent.com/24266948/48437830-85496f00-e7d6-11e8-8030-0042ed5eaf02.png)

Thanks for your time, I hope I've provided all the information necessary. Let me know if anything else is required. :)

**Comment by SonarSonic** [comment]
Fixed in dev
