### ISSUE TITLE
red stone node can't update signal in time

### ISSUE THREAD

**Issue by luoxingzlx** [SonarSonic/Practical-Logistics-2#82]
Like this
![default](https://user-images.githubusercontent.com/44374013/53163079-49f5e200-3608-11e9-8d1a-a8eda1e7e646.gif)

**Comment by LezChap** [comment]
Having the same problem.  It's behaving like it doesn't push redstone updates outside of the network itself/not causing any block updates outside the network.

**Comment by freman** [comment]
Can confirm, there's no block update.

If you do something that causes the attached block to update then the signal is passed.
